# Generated by Django 2.0.5 on 2018-05-29 10:27

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerClass', models.CharField(choices=[(polls.models.PlayerClassChoise('Rogue'), 'Rogue'), (polls.models.PlayerClassChoise('Warior'), 'Warior'), (polls.models.PlayerClassChoise('Mage'), 'Mage')], max_length=5)),
                ('playerLvl', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferedClass', models.CharField(choices=[(polls.models.PlayerClassChoise('Rogue'), 'Rogue'), (polls.models.PlayerClassChoise('Warior'), 'Warior'), (polls.models.PlayerClassChoise('Mage'), 'Mage')], max_length=5)),
                ('requiredLvl', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Quest')),
            ],
        ),
    ]
