# Generated by Django 2.0.5 on 2018-05-29 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='quest',
        ),
        migrations.AddField(
            model_name='quest',
            name='reward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Reward'),
        ),
        migrations.AddField(
            model_name='reward',
            name='artefacts',
            field=models.CharField(default='nothing', max_length=255),
            preserve_default=False,
        ),
    ]
