# Generated by Django 2.0.5 on 2018-05-29 13:51

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180529_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerClass',
            field=models.CharField(choices=[('Rogue', polls.models.PlayerClassChoise('Rogue')), ('Warior', polls.models.PlayerClassChoise('Warior')), ('Mage', polls.models.PlayerClassChoise('Mage'))], max_length=10),
        ),
    ]
