# Generated by Django 2.0.5 on 2018-05-29 14:44

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180529_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerClass',
            field=models.CharField(choices=[(polls.models.PlayerClassChoise('Rogue'), 'Rogue'), (polls.models.PlayerClassChoise('Warior'), 'Warior'), (polls.models.PlayerClassChoise('Mage'), 'Mage')], max_length=10),
        ),
    ]
